FROM node:9.3.0

RUN apt-get -y update
RUN apt-get -y install build-essential
RUN apt-get -y install wget

## RUN apk update && apk add ca-certificates wget && update-ca-certificates
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

RUN mkdir -p /app/src
WORKDIR /app

COPY package.json /app/
RUN npm install --silent
RUN npm cache clean --force --silent

COPY ./src /app/src

EXPOSE 80
